### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by brandonmcconnell** [iankberry/use-confetti-svg#1]
@iankberry I tried using the demo on codesandbox, and nothing happened when I clicked the button.

Would you mind repairing that?

**Comment by iankberry** [comment]
I'll take a look. It appears to be something about Chrome and codesandbox as it works (for me) in Firefox. It also works in Chrome if I check out the repo and run the example locally.

**Comment by iankberry** [comment]
Hi @brandonmcconnell, this should be fixed now. Feel free to re-open if you're still seeing this issue.
